#!/usr/bin/env python3
"""Generate a flame flipbook: an 8x8 sheet of 64 frames that loops.

**Procedural rather than generated by diffusion, and the reason is temporal
coherence.** A flipbook is only useful if frame N+1 looks like frame N moved a
little; a diffusion model asked for 64 flame images gives 64 unrelated ones,
and playing those back strobes. Here the frames are slices through one 3D noise
field along a closed loop, so consecutive frames are correlated by construction
and frame 63 joins back onto frame 0 with no seam.

The flame shape is not the noise. Noise alone gives a cloud; what makes fire
read as fire is that it is *narrow at the base, tapering upward, and eaten into
from the edges* — so the noise modulates an envelope rather than being the
image. The envelope also rises over the loop, which is the buoyancy the
particle motion already has, at a scale below one particle.

Usage: flipbook.py [out.png]
"""
import math
import sys

import numpy as np
from PIL import Image

GRID = 8                 # 8x8 = 64 frames
CELL = 128               # pixels per frame
LOOP_RADIUS = 11.0       # radius of the circle walked through the noise field


def value_noise_3d(shape, scale, seed):
    """Smooth value noise by upsampling a small lattice of random values."""
    rng = np.random.default_rng(seed)
    lattice = rng.random(scale)
    # Trilinear-ish upsample via repeated linear interpolation along each axis.
    out = lattice
    for axis, target in enumerate(shape):
        idx = np.linspace(0, out.shape[axis], target, endpoint=False)
        lo = np.floor(idx).astype(int) % out.shape[axis]
        hi = (lo + 1) % out.shape[axis]
        frac = (idx - np.floor(idx)).reshape(
            [-1 if a == axis else 1 for a in range(len(shape))]
        )
        out = np.take(out, lo, axis=axis) * (1 - frac) + np.take(out, hi, axis=axis) * frac
    return out


def main(path):
    # One 3D field, sampled on a circle so the last frame joins the first.
    # Two octaves: the coarse one makes the licking shapes, the fine one the
    # ragged edge.
    coarse = value_noise_3d((CELL, CELL, 24), (7, 9, 24), 12345)
    fine = value_noise_3d((CELL, CELL, 24), (17, 21, 24), 6789)

    sheet = np.zeros((GRID * CELL, GRID * CELL, 4), dtype=np.uint8)

    ys, xs = np.mgrid[0:CELL, 0:CELL]
    u = xs / (CELL - 1.0)
    v = ys / (CELL - 1.0)
    # v = 0 at the TOP of the image; the flame's base is at the bottom.
    height = 1.0 - v

    for f in range(GRID * GRID):
        t = f / float(GRID * GRID)
        # Walk a circle through the noise's third axis so the loop closes.
        z = (LOOP_RADIUS * math.cos(2 * math.pi * t) + LOOP_RADIUS) % 24
        z0, z1 = int(z) % 24, (int(z) + 1) % 24
        fz = z - int(z)
        n_c = coarse[:, :, z0] * (1 - fz) + coarse[:, :, z1] * fz
        n_f = fine[:, :, z0] * (1 - fz) + fine[:, :, z1] * fz
        n = 0.62 * n_c + 0.38 * n_f

        # The envelope: a tapering tongue. Wide and solid low down, narrowing
        # and thinning with height, and pinched to nothing at the very base so
        # a sprite does not show a hard bottom edge.
        width = 0.40 * (1.0 - height) ** 0.75 + 0.05
        radial = np.abs(u - 0.5) / np.maximum(width, 1e-4)
        envelope = np.clip(1.0 - radial ** 2, 0.0, 1.0)
        envelope *= np.clip(height * 6.0, 0.0, 1.0)          # fade in off the base
        envelope *= np.clip((1.0 - height) ** 0.35, 0.0, 1.0)  # thin toward the tip

        # Noise eats into the envelope rather than multiplying it, which is
        # what produces torn edges instead of a dimmer tongue.
        density = np.clip((envelope * (0.18 + 1.55 * n) - 0.30) * 2.4, 0.0, 1.0)

        # Hot at the base, cooling upward — a blackbody ramp, not a gradient
        # picked by eye. The alpha carries the shape; the RGB carries the
        # temperature, so the engine's own colour ramp still has something to
        # multiply.
        heat = np.clip(density * (1.25 - 0.85 * height), 0.0, 1.0)
        r = np.clip(0.35 + 1.5 * heat, 0.0, 1.0)
        g = np.clip(0.05 + 1.25 * heat ** 1.7, 0.0, 1.0)
        b = np.clip(0.02 + 0.9 * heat ** 4.0, 0.0, 1.0)

        cy, cx = divmod(f, GRID)
        tile = np.stack(
            [
                (r * 255).astype(np.uint8),
                (g * 255).astype(np.uint8),
                (b * 255).astype(np.uint8),
                (density * 255).astype(np.uint8),
            ],
            axis=-1,
        )
        sheet[cy * CELL:(cy + 1) * CELL, cx * CELL:(cx + 1) * CELL] = tile

    Image.fromarray(sheet, "RGBA").save(path)
    print(f"wrote {path}  {GRID}x{GRID} frames, {CELL}px each")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "assets/textures/fire_flipbook.png")
