"""The Blender -> Loom export contract, written once.

Every rig generator imports this rather than restating the rules. `build_boat.py`
restated them, its axis comment said the wrong thing for eight rounds, and the
boat shipped with its sidelights reversed. One copy, asserted.

    Model in Blender native Z-up.
    Export with forward_axis='NEGATIVE_Z', up_axis='Y'.
    Permutation build (x, y, z) -> obj (x, z, -y), determinant +1.
    Delivered: metres, Y up, -Z forward, +X right.

Four rules, each a scar, all enforced by `verify_obj`:

1. V is FLIPPED on export. The importer takes `vt` exactly as written
   (loom_asset/src/mesh.rs:200-208) and flips nothing. Measured 2026-08-25 with
   a red-top/blue-bottom texture on two otherwise identical quads. The failure
   is not a legible upside-down picture — it is UV islands landing on the atlas
   gutter, which reads as black patches.
2. Tags `o`/`g`/`s`/`usemtl`/`mtllib` are STRIPPED, and their absence asserted.
   A surviving tag makes `file.obj#Group` usable, and that path recentres the
   selection on its own bounding box (mesh.rs:268-276), which takes a model
   apart when the library IS one model.
3. Normals are recalculated PER SHELL by the caller before export, and
   `verify_obj` checks it PER SHELL: every connected shell's own signed volume
   must be positive. What does the work is PARTITIONING the triangles by shell,
   not the point they are summed about — signed volume is origin-invariant for a
   closed shell. A whole-mesh check is not enough —
   an outward 2 m cube plus an inverted 1 m one sums to +7 and passes, while
   that inverted shell draws pure black in Loom, diffuse and ambientVisibility
   to zero together. The whole-mesh `signed_volume` is the coarse net
   underneath; the per-shell partition is the guarantee. Both are skipped when
   `min_volume=False`, because split parts need not be closed.
4. One OBJ per material. The engine never reads `.mtl`.
"""
import os

TAGS = ("o", "g", "s", "usemtl", "mtllib")


def export_obj(obj, path, uv=True, header=""):
    """Export one object through the contract. Returns `path`."""
    import bpy

    for other in bpy.data.objects:
        other.select_set(False)
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj

    raw = path + ".raw"
    bpy.ops.wm.obj_export(
        filepath=raw,
        export_selected_objects=True,
        export_triangulated_mesh=True,
        export_normals=True,
        export_uv=uv,
        export_materials=False,
        forward_axis="NEGATIVE_Z",
        up_axis="Y",
    )

    lines = []
    if header:
        for line in header.rstrip("\n").split("\n"):
            lines.append("# " + line + "\n")
    lines.append("# Loom axes -- metres, Y up, forward -Z. V flipped on export.\n")
    lines.append("# Generated by tools/mesh/rig; never edit this file.\n")

    for line in open(raw):
        parts = line.split()
        if not parts:
            continue
        if parts[0] in TAGS:
            continue
        if parts[0] == "vt" and len(parts) >= 3:
            lines.append("vt %s %.6f\n" % (parts[1], 1.0 - float(parts[2])))
            continue
        lines.append(line)

    open(path, "w").writelines(lines)
    os.remove(raw)
    return path


def read_obj(path):
    """Parse an OBJ into plain Python. Only what Loom's own parser reads.

    `corners` pairs each face corner's vertex index with its own UV index.
    OBJ keeps `v` and `vt` as independent lists of different lengths, so
    `uvs[vertex_index]` is a bug that happens to work on a single quad and
    silently lies on anything with shared vertices.

    `faces` is the same pairs GROUPED BY FACE, which is what a per-face
    question (does this quad's UV span its own width?) needs and `corners`
    cannot answer -- `tris` has already thrown the UV indices away.
    """
    verts, uvs, tris, corners, faces, tags = [], [], [], [], [], []
    for line in open(path):
        parts = line.split()
        if not parts:
            continue
        head = parts[0]
        if head in TAGS:
            tags.append(line.rstrip("\n"))
        elif head == "v":
            verts.append(tuple(float(c) for c in parts[1:4]))
        elif head == "vt":
            uvs.append(tuple(float(c) for c in parts[1:3]))
        elif head == "f":
            idx = []
            face = []
            for spec in parts[1:]:
                bits = spec.split("/")
                i = int(bits[0])
                vi = i - 1 if i > 0 else len(verts) + i
                ti = None
                if len(bits) > 1 and bits[1]:
                    j = int(bits[1])
                    ti = j - 1 if j > 0 else len(uvs) + j
                idx.append(vi)
                corners.append((vi, ti))
                face.append((vi, ti))
            faces.append(face)
            for k in range(1, len(idx) - 1):
                tris.append((idx[0], idx[k], idx[k + 1]))
    return {"verts": verts, "uvs": uvs, "tris": tris,
            "corners": corners, "faces": faces, "tags": tags}


def signed_volume(d, tris=None, origin=(0.0, 0.0, 0.0)):
    """Sum of tetrahedron volumes to `origin`. Positive means outward.

    For a CLOSED, consistently-wound shell this is **exactly** translation-
    invariant — the divergence theorem, and measured: a unit cube 3 m from the
    origin reports +1.000000000000, and so does the same cube 1000 m away.
    Inverted, both report -1.000000000000.

    `origin` is therefore a convenience, not a correctness requirement. The
    per-shell check below passes each shell's own centroid because it keeps the
    magnitudes small and readable in a failure message, NOT because the sign
    would otherwise be wrong. An earlier version of this docstring claimed the
    origin choice was load-bearing; it was checked and it is not.
    """
    total = 0.0
    v = d["verts"]
    ox, oy, oz = origin
    for a, b, c in (d["tris"] if tris is None else tris):
        ax, ay, az = v[a]
        bx, by, bz = v[b]
        cx, cy, cz = v[c]
        ax, ay, az = ax - ox, ay - oy, az - oz
        bx, by, bz = bx - ox, by - oy, bz - oz
        cx, cy, cz = cx - ox, cy - oy, cz - oz
        total += (ax * (by * cz - bz * cy)
                  - ay * (bx * cz - bz * cx)
                  + az * (bx * cy - by * cx)) / 6.0
    return total


def shells(d):
    """Partition triangles into connected shells, by shared vertex index.

    Union-find, because that is the whole algorithm — a shell is an
    equivalence class of vertices under "appears in the same triangle", and
    the triangles follow. Returned in order of first appearance in the face
    list, so a failure message names a stable shell index.

    ponytail: connectivity is by vertex INDEX, not by position. Two shells
    that touch geometrically but do not share indices count as two, which is
    exactly what `recalc_face_normals` treats as two regions — the point of
    the check is to agree with Blender's operator, not with the geometry.
    """
    parent = list(range(len(d["verts"])))

    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    for a, b, c in d["tris"]:
        ra, rb, rc = find(a), find(b), find(c)
        parent[rb] = ra
        parent[rc] = ra

    groups = {}
    for t in d["tris"]:
        groups.setdefault(find(t[0]), []).append(t)
    return list(groups.values())


def bounds(d, tris=None):
    v = d["verts"]
    pts = v if tris is None else [v[i] for t in tris for i in t]
    lo = tuple(min(p[i] for p in pts) for i in range(3))
    hi = tuple(max(p[i] for p in pts) for i in range(3))
    return lo, hi


def verify_obj(path, *, min_volume=True):
    """Refuse anything that breaks the contract. Raises SystemExit."""
    d = read_obj(path)
    if d["tags"]:
        raise SystemExit("%s: forbidden tag survived: %r" % (path, d["tags"][:3]))
    if not d["tris"]:
        raise SystemExit("%s: no triangles" % path)
    vol = signed_volume(d)
    if min_volume:
        if vol <= 0.0:
            raise SystemExit(
                "%s: signed volume %.6f <= 0 — normals point inward and Loom will "
                "draw this pure black. Run recalc_face_normals per shell." % (path, vol))
        # **Rule 3, actually enforced.** The whole-mesh volume above is the
        # coarse net and it has a hole the size of the rule: an outward 2 m
        # cube (+8) plus an INVERTED 1 m cube (-1) sums to +7 and sails
        # through, while that second shell draws pure black — diffuse and
        # ambientVisibility to zero together. Only a per-shell volume, about
        # each shell separately, sees it. The centroid is used only to keep the
        # reported magnitude small; the sign does not depend on it. Guarded by
        # `min_volume` like the
        # global check, because split parts are legitimately not closed.
        for i, tris in enumerate(shells(d)):
            idx = {v for t in tris for v in t}
            centroid = tuple(sum(d["verts"][j][k] for j in idx) / len(idx)
                             for k in range(3))
            sv = signed_volume(d, tris, centroid)
            if sv <= 0.0:
                slo, shi = bounds(d, tris)
                raise SystemExit(
                    "%s: shell %d of %d has signed volume %.6f <= 0 about its "
                    "own centroid (%.3f, %.3f, %.3f) — %d tris, bounds "
                    "%.3f..%.3f x %.3f..%.3f x %.3f..%.3f. Its normals point "
                    "INWARD and Loom will draw it pure black, while the "
                    "whole-mesh volume %.6f hides it. Run "
                    "recalc_face_normals per shell."
                    % (path, i, len(shells(d)), sv, centroid[0], centroid[1],
                       centroid[2], len(tris), slo[0], shi[0], slo[1], shi[1],
                       slo[2], shi[2], vol))
    lo, hi = bounds(d)
    return {"tris": len(d["tris"]), "verts": len(d["verts"]),
            "lo": lo, "hi": hi, "volume": vol}
