"""The Blender -> Loom export contract, written once.

Every rig generator imports this rather than restating the rules. `build_boat.py`
restated them, its axis comment said the wrong thing for eight rounds, and the
boat shipped with its sidelights reversed. One copy, asserted.

    Model in Blender native Z-up.
    Export with forward_axis='NEGATIVE_Z', up_axis='Y'.
    Permutation build (x, y, z) -> obj (x, z, -y), determinant +1.
    Delivered: metres, Y up, -Z forward, +X right.

Four rules, each a scar, all enforced by `verify_obj`:

1. V is FLIPPED on export. The importer takes `vt` exactly as written
   (loom_asset/src/mesh.rs:200-208) and flips nothing. Measured 2026-08-25 with
   a red-top/blue-bottom texture on two otherwise identical quads. The failure
   is not a legible upside-down picture — it is UV islands landing on the atlas
   gutter, which reads as black patches.
2. Tags `o`/`g`/`s`/`usemtl`/`mtllib` are STRIPPED, and their absence asserted.
   A surviving tag makes `file.obj#Group` usable, and that path recentres the
   selection on its own bounding box (mesh.rs:268-276), which takes a model
   apart when the library IS one model.
3. Normals are recalculated PER SHELL by the caller before export. A whole-mesh
   signed-volume check passes while most of a surface points inward, and Loom
   draws that pure black — diffuse and ambientVisibility go to zero together.
   `signed_volume` here is the coarse net underneath, not the guarantee.
4. One OBJ per material. The engine never reads `.mtl`.
"""
import os

TAGS = ("o", "g", "s", "usemtl", "mtllib")


def export_obj(obj, path, uv=True, header=""):
    """Export one object through the contract. Returns `path`."""
    import bpy

    for other in bpy.data.objects:
        other.select_set(False)
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj

    raw = path + ".raw"
    bpy.ops.wm.obj_export(
        filepath=raw,
        export_selected_objects=True,
        export_triangulated_mesh=True,
        export_normals=True,
        export_uv=uv,
        export_materials=False,
        forward_axis="NEGATIVE_Z",
        up_axis="Y",
    )

    lines = []
    if header:
        for line in header.rstrip("\n").split("\n"):
            lines.append("# " + line + "\n")
    lines.append("# Loom axes -- metres, Y up, forward -Z. V flipped on export.\n")
    lines.append("# Generated by tools/mesh/rig; never edit this file.\n")

    for line in open(raw):
        parts = line.split()
        if not parts:
            continue
        if parts[0] in TAGS:
            continue
        if parts[0] == "vt" and len(parts) >= 3:
            lines.append("vt %s %.6f\n" % (parts[1], 1.0 - float(parts[2])))
            continue
        lines.append(line)

    open(path, "w").writelines(lines)
    os.remove(raw)
    return path


def read_obj(path):
    """Parse an OBJ into plain Python. Only what Loom's own parser reads.

    `corners` pairs each face corner's vertex index with its own UV index.
    OBJ keeps `v` and `vt` as independent lists of different lengths, so
    `uvs[vertex_index]` is a bug that happens to work on a single quad and
    silently lies on anything with shared vertices.
    """
    verts, uvs, tris, corners, tags = [], [], [], [], []
    for line in open(path):
        parts = line.split()
        if not parts:
            continue
        head = parts[0]
        if head in TAGS:
            tags.append(line.rstrip("\n"))
        elif head == "v":
            verts.append(tuple(float(c) for c in parts[1:4]))
        elif head == "vt":
            uvs.append(tuple(float(c) for c in parts[1:3]))
        elif head == "f":
            idx = []
            for spec in parts[1:]:
                bits = spec.split("/")
                i = int(bits[0])
                vi = i - 1 if i > 0 else len(verts) + i
                ti = None
                if len(bits) > 1 and bits[1]:
                    j = int(bits[1])
                    ti = j - 1 if j > 0 else len(uvs) + j
                idx.append(vi)
                corners.append((vi, ti))
            for k in range(1, len(idx) - 1):
                tris.append((idx[0], idx[k], idx[k + 1]))
    return {"verts": verts, "uvs": uvs, "tris": tris,
            "corners": corners, "tags": tags}


def signed_volume(d):
    """Sum of tetrahedron volumes to the origin. Positive means outward."""
    total = 0.0
    v = d["verts"]
    for a, b, c in d["tris"]:
        ax, ay, az = v[a]
        bx, by, bz = v[b]
        cx, cy, cz = v[c]
        total += (ax * (by * cz - bz * cy)
                  - ay * (bx * cz - bz * cx)
                  + az * (bx * cy - by * cx)) / 6.0
    return total


def bounds(d):
    v = d["verts"]
    lo = tuple(min(p[i] for p in v) for i in range(3))
    hi = tuple(max(p[i] for p in v) for i in range(3))
    return lo, hi


def verify_obj(path, *, min_volume=True):
    """Refuse anything that breaks the contract. Raises SystemExit."""
    d = read_obj(path)
    if d["tags"]:
        raise SystemExit("%s: forbidden tag survived: %r" % (path, d["tags"][:3]))
    if not d["tris"]:
        raise SystemExit("%s: no triangles" % path)
    vol = signed_volume(d)
    if min_volume and vol <= 0.0:
        raise SystemExit(
            "%s: signed volume %.6f <= 0 — normals point inward and Loom will "
            "draw this pure black. Run recalc_face_normals per shell." % (path, vol))
    lo, hi = bounds(d)
    return {"tris": len(d["tris"]), "verts": len(d["verts"]),
            "lo": lo, "hi": hi, "volume": vol}
