# tools/mesh/rig/split_parts.py
"""Split one multi-material OBJ into one whole-file OBJ per material.

`build_boat.py:77` names this file as the thing that produced the boat's 21
per-material OBJs. It did not survive the migration to Omarchy; the outputs did
and the script did not. This is a rebuild from the contract its outputs imply.

**Whole files, never `#Group`.** Loom can address one object inside a multi-object
OBJ with `path.obj#Name`, and that path recentres the selection on its own
bounding box -- X and Z to the centre, Y to the minimum (loom_asset/src/mesh.rs
:268-276). That is right for a tree library and catastrophic for one model split
into parts: every part snaps to its own centroid and the model comes apart. So
each output here keeps the source's authored coordinates and carries no tag at
all, which makes the fragment path unusable and the mistake loud.

The vertex list is rewritten per part rather than shared, because a part that
carries the whole model's `v` list is a part that costs the whole model's memory
twenty times over.

Run: python3 split_parts.py <src.obj> <out_dir> <prefix>
"""
import os
import sys

import rigkit


def split(src, out_dir, prefix):
    """-> {material: path}. Raises SystemExit if the source names no material."""
    verts, uvs, norms = [], [], []
    parts = {}          # material -> list of face specs, each a list of "v/vt/vn"
    current = None

    for line in open(src):
        f = line.split()
        if not f:
            continue
        head = f[0]
        if head == "v":
            verts.append(tuple(float(c) for c in f[1:4]))
        elif head == "vt":
            uvs.append(tuple(float(c) for c in f[1:3]))
        elif head == "vn":
            norms.append(tuple(float(c) for c in f[1:4]))
        elif head == "usemtl":
            current = f[1]
            parts.setdefault(current, [])
        elif head == "f":
            if current is None:
                raise SystemExit(
                    "%s: a face appears before any `usemtl`. Every face must "
                    "belong to a named material, because a material is the unit "
                    "of separation here." % src)
            parts[current].append(f[1:])

    if not parts:
        raise SystemExit(
            "%s: no `usemtl` in the file, so there is nothing to split by. The "
            "engine reads no .mtl and takes one OBJ per material; a single-"
            "material part should be exported directly instead." % src)

    written = {}
    for mat, faces in parts.items():
        # Renumber: collect only the elements this part actually references.
        vmap, tmap, nmap = {}, {}, {}
        out = ["# %s: %s. Loom axes -- metres, Y up, forward -Z.\n" % (prefix, mat),
               "# One OBJ per material: the engine reads no .mtl, and a `#Group`\n",
               "# selector would recentre this part on its own bounding box.\n",
               "# Generated by tools/mesh/rig/split_parts.py; never edit.\n"]

        def keep(store, table, source, idx):
            """1-based OBJ index -> 1-based index in this part's own list."""
            key = idx - 1 if idx > 0 else len(source) + idx
            if key not in table:
                table[key] = len(table) + 1
                store.append(source[key])
            return table[key]

        pv, pt, pn = [], [], []
        specs = []
        for face in faces:
            spec = []
            for corner in face:
                bits = (corner.split("/") + ["", ""])[:3]
                vi = keep(pv, vmap, verts, int(bits[0]))
                ti = keep(pt, tmap, uvs, int(bits[1])) if bits[1] else None
                ni = keep(pn, nmap, norms, int(bits[2])) if bits[2] else None
                if ti and ni:
                    spec.append("%d/%d/%d" % (vi, ti, ni))
                elif ni:
                    spec.append("%d//%d" % (vi, ni))
                elif ti:
                    spec.append("%d/%d" % (vi, ti))
                else:
                    spec.append("%d" % vi)
            specs.append(spec)

        for x, y, z in pv:
            out.append("v %.6f %.6f %.6f\n" % (x, y, z))
        for u, v in pt:
            out.append("vt %.6f %.6f\n" % (u, v))
        for x, y, z in pn:
            out.append("vn %.4f %.4f %.4f\n" % (x, y, z))
        for spec in specs:
            out.append("f " + " ".join(spec) + "\n")

        path = os.path.join(out_dir, "%s_%s.obj" % (prefix, mat))
        open(path, "w").writelines(out)
        rigkit.verify_obj(path, min_volume=False)   # a part need not be closed
        written[mat] = path

    return written


if __name__ == "__main__":
    if len(sys.argv) != 4:
        raise SystemExit("usage: split_parts.py <src.obj> <out_dir> <prefix>")
    for mat, path in sorted(split(sys.argv[1], sys.argv[2], sys.argv[3]).items()):
        info = rigkit.verify_obj(path, min_volume=False)
        print("%-16s %6d tris  %s" % (mat, info["tris"], path))
