import re, pathlib

src = open('xtask/src/main.rs').read()

def block(name):
    i = src.index(f'const {name}')
    j = src.index('];', i)
    return set(re.findall(r'"(assets/[a-z_]+/[a-z_0-9]+\.loom)"', src[i:j]))

scenes, golden = block('SCENES'), block('GOLDEN')

# The CPU-budget list is a third gate and worth showing.
i = src.index('for scene in [\n            "assets/test/forest.loom"')
budget = set(re.findall(r'"(assets/[a-z_]+/[a-z_0-9]+\.loom)"', src[i:i+600]))

def summary(p):
    """First sentence of the scene's header comment."""
    out = []
    for line in pathlib.Path(p).read_text(errors='ignore').splitlines():
        if not line.startswith('#'):
            break
        t = line.lstrip('#').strip()
        if t:
            out.append(t)
        elif out:
            break
    text = ' '.join(out)
    text = re.sub(r'\*\*|`', '', text)
    m = re.match(r'(.{0,150}?[.。])(\s|$)', text)
    return (m.group(1) if m else text[:150]).strip()

rows = []
for p in sorted(str(x) for x in pathlib.Path('assets').rglob('*.loom')):
    gates = []
    if p in golden: gates.append('image')
    if p in scenes: gates.append('validate')
    if p in budget: gates.append('cpu')
    rows.append((p, ','.join(gates) or '—', summary(p)))

lines = [
    '# The scene library',
    '',
    'Generated by `tools/scene_index.py`. Re-run it after adding or removing a scene.',
    '',
    '**Gates** — what actually checks the scene, which is the only reason most of these exist:',
    '',
    '- `image` — in `GOLDEN`: its pixels are compared against `tests/references/` every run.',
    '  A scene belongs here when it covers a **rendering path** nothing else covers.',
    '- `validate` — in `SCENES`: rendered by `cargo xtask validate`, which requires zero Vulkan',
    '  validation messages. Catches API misuse, not appearance.',
    '- `cpu` — in the `--play` frame-budget list: measured against 30 ms/frame.',
    '- `—` — in no gate. Either a fixture a Rust test loads directly, or something nothing',
    '  guards. The second kind is where rot accumulates.',
    '',
    f'{len(rows)} scenes: {len(golden)} in the image gate, {len(scenes)} in validate.',
    '',
    '| scene | gates | what it is for |',
    '| --- | --- | --- |',
]
for p, g, s in rows:
    lines.append(f'| `{p.removeprefix("assets/")}` | {g} | {s} |')

pathlib.Path('assets/SCENES.md').write_text('\n'.join(lines) + '\n')
print(f'wrote assets/SCENES.md — {len(rows)} scenes')
for p, g, s in rows:
    if g == '—':
        print(f'  ungated: {p}')
