[package]
name = "loom_cli"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "loom"
path = "src/main.rs"

[dependencies]
loom_asset = { version = "0.0.0", path = "../loom_asset" }
loom_ecs = { version = "0.0.0", path = "../loom_ecs" }
loom_input = { version = "0.0.0", path = "../loom_input" }
loom_physics = { version = "0.0.0", path = "../loom_physics" }
loom_render = { version = "0.0.0", path = "../loom_render" }
loom_scene = { version = "0.0.0", path = "../loom_scene" }
loom_script = { version = "0.0.0", path = "../loom_script" }
loom_voxel = { version = "0.0.0", path = "../loom_voxel" }
serde = "=1.0.229"
serde_json = "=1.0.151"
winit = "=0.30.13"
